name: Production Deployment

on:
  push:
    branches:
      - main

concurrency: 
  group: production_deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying Vevada Stack via SSH
        uses: appleboy/ssh-action@7eaf76671a0d7eec5d98ce8ee3ada08452bf52c8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          script: |
            set -e
            cd ~/Vevada
            git pull origin main
            docker compose up -d --build
